minimum_pre_commit_version: 2.13.0
exclude: ^\.(html|csv|svg|bib)$
ci:
    autofix_prs: false
repos:
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
            - flake8-comprehensions==3.1.0
            - pandas-dev-flaker==0.3.0
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
